class UserRepository:
    async def get_user(self, username): ...
    async def create_user(self, username, password): ...
    async def save_refresh_token(self, token): ...
    async def is_token_blacklisted(self, token): ...
    async def blacklist_token(self, token): ...